version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./ddl_statements.sql:/docker-entrypoint-initdb.d/ddl_statements.sql
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
